In [2]:
%load_ext autoreload
%autoreload 2

In [3]:
from __future__ import print_function, division, absolute_import

In [4]:
import inspect

In [5]:
import numpy as np

In [6]:
from wgomoku import GomokuTools as gt, SampleDataHelper

/home/wgiersche/workspace/DeepGomoku/tf2/lib/python3.5/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/wgiersche/workspace/DeepGomoku/tf2/lib/python3.5/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/wgiersche/workspace/DeepGomoku/tf2/lib/python3.5/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/wgiersche/workspace/De

In [7]:
import tensorflow as tf
print(tf.__version__)
tf.test.is_gpu_available()

2.0.0-beta1


True

In [8]:
N=11

In [9]:
sdh = SampleDataHelper(N)

In [10]:
def disp(sample):
    if tf.is_tensor(sample):
        sample = sample.numpy()
    s = np.rollaxis(sample, -1, 0)
    return str(s[0]+2*s[1])

In [11]:
board = "a1a2f6g7e7"

---
Coordinates of that board's stones on a padded (here:=13x13) numpy tensor:

In [12]:
print(inspect.getsource(sdh.padded_coords))

    def padded_coords(self, board):
        """
        return stones in matrix coordinates respecting the border padding
        """
        stones = gt.string_to_stones(board)
        matrix_coords = [gt.b2m([ord(s[0])-64, s[1]], self.N) for s in stones]
        return np.add(matrix_coords, [1,1])



In [13]:
coords = sdh.padded_coords(board)
coords

array([[11,  1],
       [10,  1],
       [ 6,  6],
       [ 5,  7],
       [ 5,  5]])

---
An empty board's representation:

In [14]:
print(inspect.getsource(sdh.template))

    def template(self):
        """
        create a fresh empty board representation
        """
        s = np.zeros([self.N,self.N], dtype=np.int16)
        defensive = np.pad(s, pad_width=1, constant_values=1)
        offensive = np.zeros([self.N+2, self.N+2], dtype=np.int16)
        template = np.stack([offensive, defensive], axis=-1)
        return template



In [15]:
# need to change the position of the channel axis to display the board nicely
np.rollaxis(sdh.template(), 2, 0)

array([[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

       [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
        [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
        [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
        [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
        [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
        [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
        [1, 0, 0, 

In [16]:
some_board = sdh.template()
some_board[6,6,0] = 1
some_board[7,7,1] = 1 
print(disp(some_board))

[[2 2 2 2 2 2 2 2 2 2 2 2 2]
 [2 0 0 0 0 0 0 0 0 0 0 0 2]
 [2 0 0 0 0 0 0 0 0 0 0 0 2]
 [2 0 0 0 0 0 0 0 0 0 0 0 2]
 [2 0 0 0 0 0 0 0 0 0 0 0 2]
 [2 0 0 0 0 0 0 0 0 0 0 0 2]
 [2 0 0 0 0 0 1 0 0 0 0 0 2]
 [2 0 0 0 0 0 0 2 0 0 0 0 2]
 [2 0 0 0 0 0 0 0 0 0 0 0 2]
 [2 0 0 0 0 0 0 0 0 0 0 0 2]
 [2 0 0 0 0 0 0 0 0 0 0 0 2]
 [2 0 0 0 0 0 0 0 0 0 0 0 2]
 [2 2 2 2 2 2 2 2 2 2 2 2 2]]


---
Eight equivalent boards for the symmetry operations: rotate 90/180/270 and flip

In [17]:
print(inspect.getsource(sdh.rot_flip))

    def rot_flip (self, coords, quarters, flip):
        """
        coords: list of tuples of matrix coordinates
        quarters: multiples of 90 degrees to rotate
        flip: boolean: Flip or not
        """
        N = self.N+2
        r,c = np.transpose(coords)
        quarters = quarters % 4
        if quarters == 0:
            res = (r,c)
        elif quarters == 1:
            res = (N-c-1, r)
        elif quarters == 2:
            res = (N-r-1,N-c-1)
        elif quarters == 3:
            res = (c, N-r-1)
        if flip:
            res = res[::-1]
        return np.transpose(res)



In [18]:
print(coords)
sdh.rot_flip(coords, quarters=1, flip=False)

[[11  1]
 [10  1]
 [ 6  6]
 [ 5  7]
 [ 5  5]]


array([[11, 11],
       [11, 10],
       [ 6,  6],
       [ 5,  5],
       [ 7,  5]])

In [19]:
print(inspect.getsource(sdh.all_symmetries))

    def all_symmetries(self, coords):
        """
        All 8 equivalent game plays
        coords: border-padded coordinates
        """
        return [
            self.rot_flip(coords, quarters=quarters, flip=flip) 
            for quarters in range(4) for flip in [False, True]
        ]



In [20]:
all_traj = sdh.all_symmetries(coords)
all_traj

[array([[11,  1],
        [10,  1],
        [ 6,  6],
        [ 5,  7],
        [ 5,  5]]), array([[ 1, 11],
        [ 1, 10],
        [ 6,  6],
        [ 7,  5],
        [ 5,  5]]), array([[11, 11],
        [11, 10],
        [ 6,  6],
        [ 5,  5],
        [ 7,  5]]), array([[11, 11],
        [10, 11],
        [ 6,  6],
        [ 5,  5],
        [ 5,  7]]), array([[ 1, 11],
        [ 2, 11],
        [ 6,  6],
        [ 7,  5],
        [ 7,  7]]), array([[11,  1],
        [11,  2],
        [ 6,  6],
        [ 5,  7],
        [ 7,  7]]), array([[1, 1],
        [1, 2],
        [6, 6],
        [7, 7],
        [5, 7]]), array([[1, 1],
        [2, 1],
        [6, 6],
        [7, 7],
        [7, 5]])]

---
Create samples from the trajectory using Bellmann rollout:

In [21]:
print(inspect.getsource(sdh.traj_to_samples))

    def traj_to_samples(self, traj, terminal_value, gamma):
        """
        creates samples for a given trajectory, together with the bellmann-values

        traj: trajectory, represented by their padded coordinates
        terminal_value: the given value of the last state in the trajectory
        gamma: discount factor. 
        """
        samples = []
        values = []
        value = terminal_value
        to_move_first = 1
        for t in range(len(traj)):      
            to_move = to_move_first
            moves = traj[:t+1]
            sample = self.template()
            for move in moves:
                sample[move[0], move[1], to_move] = 1
                to_move = 1 - to_move
            samples.append(sample)
            values.append(value)
            # Actually, this is the wrong order, we'll invert before returning
            if to_move_first == 0:
                value = - value
            else:
                value = - gamma * value
            to_move_

Order of the dimensions: (Batch, rows, cols, channels)

In [22]:
samples, values = sdh.traj_to_samples(all_traj[0], terminal_value=1, gamma=.9)
np.shape(samples)

(5, 13, 13, 2)

In [23]:
print(values)

[0.81, -0.81, 0.9, -0.9, 1]


In [24]:
print(disp(samples[1]), values[1])

[[2 2 2 2 2 2 2 2 2 2 2 2 2]
 [2 0 0 0 0 0 0 0 0 0 0 0 2]
 [2 0 0 0 0 0 0 0 0 0 0 0 2]
 [2 0 0 0 0 0 0 0 0 0 0 0 2]
 [2 0 0 0 0 0 0 0 0 0 0 0 2]
 [2 0 0 0 0 0 0 0 0 0 0 0 2]
 [2 0 0 0 0 0 0 0 0 0 0 0 2]
 [2 0 0 0 0 0 0 0 0 0 0 0 2]
 [2 0 0 0 0 0 0 0 0 0 0 0 2]
 [2 0 0 0 0 0 0 0 0 0 0 0 2]
 [2 2 0 0 0 0 0 0 0 0 0 0 2]
 [2 1 0 0 0 0 0 0 0 0 0 0 2]
 [2 2 2 2 2 2 2 2 2 2 2 2 2]] -0.81


---
Now, from the string rep to all 40 board/value pairs, ready to be fed in to a neural network:

In [25]:
print(inspect.getsource(sdh.from_string_with_bellmann))

    def from_string_with_bellmann(self, board, terminal_value=None, gamma=1.0):
        """
        Creates an symmetry-augmented dataset of board positions and their values.
        Values are calculated as Bellmann rollouts backwards from terminal_value with alternating 
        signs using discount factor gamma.
        The samples will have shape [N_moves*8, N+2, N+2, 2]

        If terminal_value is 1, expect the values to be [..., gamma^2, -gamma, gamma, -1, 1]

        board: The string rep of the stones, like e.g. "j10k11i9"
        N: the size of the board
        """
        
        # stones in matrix coordinates respecting the border padding
        padded_stones = self.padded_coords(board)

        # all equivalent representations: 4xrot, 2xflip = 8 variants 
        all_traj = self.all_symmetries(padded_stones)
        
        all_samples = []
        all_values = []
        for traj in all_traj:
            samples, values = self.traj_to_samples(traj, 
                 

In [29]:
samples, values = sdh.from_string_with_bellmann(board, gamma=.9, terminal_value=1)
print(np.shape(samples))

probe=0
print(disp(samples[probe]), values[probe])

(40, 13, 13, 2)
[[2 2 2 2 2 2 2 2 2 2 2 2 2]
 [2 0 0 0 0 0 0 0 0 0 0 0 2]
 [2 0 0 0 0 0 0 0 0 0 0 0 2]
 [2 0 0 0 0 0 0 0 0 0 0 0 2]
 [2 0 0 0 0 0 0 0 0 0 0 0 2]
 [2 0 0 0 0 0 0 0 0 0 0 0 2]
 [2 0 0 0 0 0 0 0 0 0 0 0 2]
 [2 0 0 0 0 0 0 0 0 0 0 0 2]
 [2 0 0 0 0 0 0 0 0 0 0 0 2]
 [2 0 0 0 0 0 0 0 0 0 0 0 2]
 [2 0 0 0 0 0 0 0 0 0 0 0 2]
 [2 2 0 0 0 0 0 0 0 0 0 0 2]
 [2 2 2 2 2 2 2 2 2 2 2 2 2]] 0.81
